name: Buildx, Extract & Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image for amd64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          load: true
          tags: shahanafarooqui/clnrest:${{ github.event.release.tag_name }}-amd64

      - name: Create containers and extract binaries
        run: |
          docker create --name temp-amd64 shahanafarooqui/clnrest:${{ github.event.release.tag_name }}-amd64
          docker cp temp-amd64:/release/clnrest ./clnrest-${{ github.event.release.tag_name }}-amd64
          docker cp temp-amd64:/release/cln_rest ./cln_rest-${{ github.event.release.tag_name }}-amd64
          docker rm temp-amd64

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./clnrest-${{ github.event.release.tag_name }}-amd64
          asset_name: clnrest-${{ github.event.release.tag_name }}-amd64
          asset_content_type: application/octet-stream
